export { createPatchRouter, createStateEngine, createStatePatchEnvelope } from './subscription.js';
export { mapPath, mapTextPosition, mapTextPositions } from './path-map.js';

export type {
  DeltaView,
  DeltaViewOptions,
  DiffOptions,
  DirtyRowsFrontier,
  JsonArray,
  JsonObject,
  JsonPath,
  JsonPrimitive,
  JsonValue,
  MapPathOptions,
  ObjectKey,
  Patch,
  PatchOperation,
  PatchRouter,
  PatchSubscription,
  PatchWatchCallback,
  PathSegment,
  StateBasisToken,
  StateCommitWithBasisOptions,
  StateEngine,
  StateEngineOptions,
  StatePatchCommitOptions,
  StatePatchCommitReason,
  StatePatchCommitResult,
  StatePatchCommitStatus,
  StatePatchEnvelope,
  StatePatchEnvelopeOptions,
  StatePatchInput,
  StatePatchStaleMode,
  TextPosition,
  WatchOptions,
  WatchPath,
  WatchRange
} from './types.js';
